### PR TITLE
Improve crawler logging

### PR DESCRIPTION
**Pull request by tw4l**
Connected to https://github.com/webrecorder/browsertrix-crawler/issues/74

Related to https://github.com/webrecorder/browsertrix-cloud/issues/330

This PR improves browsertrix-crawler logging. Changes:

- Add Logger class with methods for info, error, warn, and debug
- Replace `console.log`, `console.warn` and `console.error` with appropriate logger methods
- Log messages as [JSON Lines](https://jsonlines.org/) with the following structure:
    - info - general:
    ```
    {"logLevel":"info","timestamp":"2022-12-21T17:58:36.114Z","context":"general","message":"Seeds","details":[{"url":"https://webrecorder.net/","include":[{}],"exclude":[],"scopeType":"prefix","sitemap":false,"allowHash":false,"maxExtraHops":1,"maxDepth":99999}]}
    ```
    - info - pageGraph:
    ```
    {"logLevel":"info","timestamp":"2022-12-21T17:58:45.601Z","context":"pageGraph","message":"Page graph data for successfully crawled page","details":{"url":"https://webrecorder.net/","seedId":0,"depth":0,"started":"2022-12-21T17:58:36.586Z"}}
    ```
    - info - behavior:
    ```
    {"logLevel":"info","timestamp":"2022-12-21T17:59:42.914Z","context":"behavior","message":"Behavior line","details":{"state":{"tweets":1,"images":3,"videos":0},"msg":"Capturing Tweet: https://twitter.com/DaleLore/status/1600896285124399104?cxt=HHwWgMCo0Y-sw7csAAAA"}}
    ```
    - error:
    ```
    {"logLevel":"error","timestamp":"2022-12-21T18:00:01.096Z","context":"general","message":"Failed to load resource: the server responded with a status of 404 (Not Found)","details":{"location":{"url":"https://webrecorder.net/2021/01/04/assets/favicon.ico"}}}
    ```
    - warn:
    ```
    {"logLevel":"warn","timestamp":"2022-12-21T18:07:22.868Z","context":"general","message":"Page Load Failed: https://docnow.io/","details":{"message":"Timeout hit: 180000"}}
    ```
- Remove puppeteer-cluster stats
- Log behaviors by default
- Amend argParser to reflect logging changes

Sample log for a page crawl of https://webrecorder.net with `--extraHops 1`: [webrecorder-sample-log-simple.txt](https://github.com/webrecorder/browsertrix-crawler/files/10280291/webrecorder-sample-log-simple.txt)

### CODE REVIEW

**Comment by ikreymer** [comment]
Great! We probably want the actual logs to be on a single line, right?
And then converting all existing logging to use the format (no more random lines of text in the output!)

**Comment by tw4l** [comment]
> Great! We probably want the actual logs to be on a single line, right?

Yup! Printing each json-l object on its own line is just a matter of passing an option to `util.inspect`, which the latest commit shows :)

Turning my attention to those random lines now - for the child_processes we can probably just add some handlers to capture the output and then write it to the logs via the logger object.

**Comment by ikreymer** [comment]
Wonder if we should readd the puppeteer cluster stats, or at least something similar, with maybe a context of "crawlState" that would include some of the stats that it printed, mainly: crawled pages, total pages, list of current pages?
This is obtainable from the crawl state object, similar to what puppeteer cluster does. The other data there (cpu, time  estimates) is not that accurate so probably don't need to include that.
Do we want to be able to filter by the different types of info here? Or make another level, such as 'verbose' that would include this? Hm

**Comment by ikreymer** [comment]
Some other things to decide also, what should be the default for command-line usage, vs the default for running in browsertrix cloud. For example, the crawlState maybe we want to have printed periodically (like puppeteer-cluster) when running via command-line, but may be redundant when running in the cloud since that data will be available via the UI..
Also wondering about JS errors, and we should treat them separately (eg. under verbose level), as user may not necessarily want to see them..

**Comment by tw4l** [comment]
Hm, good points! It seems like maybe the simplest thing to do would be to add `stats` (new implementation per @ikreymer 's note above without CPU and time estimate and with `crawlState` context) and `jserrors` back to the `--logging` CLI open, and include `stats` by default.

That keeps it more similar to the previous API and seems more configurable than a single `verbose` option - e.g. Browsertrix Cloud can simply omit the `stats` option.

**Comment by tw4l** [comment]
Updated logging examples.

Domain crawl of https://bitarchivist.net, default `--logging` options, with new crawl statistics implementation:
[logging-stats-default.txt](https://github.com/webrecorder/browsertrix-crawler/files/10386337/logging-stats-default.txt)

Domain crawl of https://bitarchivist.net, with `--logging jserrors`:
[logging-jserrors-no-stats.txt](https://github.com/webrecorder/browsertrix-crawler/files/10386343/logging-jserrors-no-stats.txt)

**Comment by tw4l** [comment]
One last detail: the outputs of thrown `Error`s won't be formatted as JSON as they break execution.

@ikreymer what would you think about replacing the few thrown `Error`s with a method to log the error message and then quit execution - perhaps `Logger.fatalError()`?

**Comment by tw4l** [comment]
I implemented `Logger.fatal()` in https://github.com/webrecorder/browsertrix-crawler/pull/195/commits/025625b11ece8ec1a3a5b69dcaad14c649b0c673. There might be room for improvement eventually with trying to quit more gracefully, but this at least ensures that all stdout should be formatted in JSON and gives the user a clear idea why a crawl failed.

**Review by ikreymer — APPROVED** [review]
Looks great, the new fatal logging before exit is a great to have as well1

**Pull request merged**
