### PR TITLE
Get rid of Python dependencies now that pywb is gone

### PR DESCRIPTION
**Pull request by benoit74**
As far as I've understood, pywb is not used anymore now.

We however still have few Python dependencies which AFAIK are not used by the crawler anymore. I propose to get rid of them since this will make life easier to migrate to Ubuntu Noble

### CODE REVIEW

**Comment by benoit74** [comment]
This is ready for review

**Comment by benoit74** [comment]
Hum, looks like Python is still used for cdxj indexer ... so this will have to be fixed indeed. Not ready for review then, sorry.

**Comment by benoit74** [comment]
Closing this in favor of https://github.com/webrecorder/browsertrix-crawler/pull/591

**Comment by tw4l** [comment]
> Hum, looks like Python is still used for cdxj indexer ... so this will have to be fixed indeed. Not ready for review then, sorry.

Yes at this point it's still used to create WACZ files. That should change soon with a switch to js-wacz however :) Thanks for the PRs!

**Pull request closed without merging**
