### PR TITLE
HTTP Basic Auth

### LINKED ISSUE #168: HTTP Basic Auth profile?
Is it possible to crawl a site that has had HTTP Basic Authentication turned on? When I try to create a profile I get an error:

```
docker run -p 9222:9222 -p 9223:9223 -v $PWD/profiles:/output/ -it webrecorder/browsertrix-crawler create-login-profile --interactive --url "http://www.buffon.cnrs.fr"
Launching XVFB
loading
/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Frame.js:225
                    ? new Error(`${response.errorText} at ${url}`)
                      ^

Error: net::ERR_INVALID_AUTH_CREDENTIALS at http://www.buffon.cnrs.fr
    at navigate (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Frame.js:225:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Frame.goto (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Frame.js:195:21)
    at async Page.goto (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Page.js:1155:16)
    at async main (/app/create-login-profile.js:161:3)
```

Then I tried to create a profile by starting at one place and then navigating to the desired location. I see in the devtools console that a HTTP 401 response has been sent, but the popup to log in does not appear.

Screen Shot 2022-09-22 at 11 35 27 AM

### PR DESCRIPTION
**Pull request by edsu**
Adds `--httpUser` and `--httpPassword` for HTTP Basic Authentication support.

Closes #168

### CODE REVIEW

**Comment by edsu** [comment]
I was trying to implement support for HTTP Basic Auth, and got a simple puppeteer-cluster example working, but when I tried to do the same thing in `crawler.js` I seemed to run into a problem where the `authenticate()` call seems to have no effect? I can see that it is getting called correctly with username and password, but I can also see from the WARC request record that Authorization is not being sent.

Is there something in the browser configuration that is preventing HTTP Basic Auth?

**Review by stavares843 — COMMENTED** [review]
The changes have been made in two files crawler.js and argParser.js.
In crawler.js, a new condition has been added to check if httpUser and httpPassword are present in the parameters. If they are present, the httpBasicAuth object is created using the provided username and password.
If httpBasicAuth is present, then it is used to authenticate the page request using the page.authenticate() method.
In argParser.js, two new options httpUser and httpPassword have been added to the options object. These options allow the user to specify the username and password for HTTP Basic Authentication.
The code changes look good.

**Comment by edsu** [comment]
@stavares843 unfortunately the changes don't seem to work though! I was looking for feedback on what might be wrong.

**Comment by vnznznz** [comment]
I managed to successfully crawl http://
httpbin.org/basic-auth/foo/bar by directly creating the required `Autorization` header instead of using `page.authenticate` in `loadPage`.

``` javascript
    if (this.httpBasicAuth) {
      logger.info(`Using HTTP Basic Auth: ${JSON.stringify(this.httpBasicAuth)}`)
      var encodedAuth = btoa(this.httpBasicAuth.username + ":" + this.httpBasicAuth.password);
      page.setExtraHTTPHeaders({Authorization: "Basic " + encodedAuth });
    }
```

**Comment by ikreymer** [comment]
> Hmm I wonder if this will work better now that pywb is out of the picture and puppeteer is getting content directly?

Yes, it should definitely! Though, this needs to be refactored on the latest, and perhaps we can add it to 1.2.0 release!

**Comment by edsu** [comment]
It was a bit easier for me to start fresh after almost a 2 years. See #566

**Pull request closed without merging**
