### PR TITLE
Implemented option for FullPage screenshot after the behaviours have run

### PR DESCRIPTION
**Pull request by fservida**
This PR implements a new option to take the FullPage screenshot **after** the behaviours have run instead of before.
This allows to capture elements that might not be fully loaded until the whole page is visited.

I only implemented for fullpage as I think it is the only screenshot where this is useful and the only case where I would need it, as it can include content not currently in frame. Feel free to expand on that as needed.

Related to #486

Tested with custom docker, though I had to ensure setuptools v71 as else it would not build.

### CODE REVIEW

**Comment by ikreymer** [comment]
Thanks for this - i think it would be clearer if it was part of the existing `--screenshot` flag, perhaps called `fullPageAfterBehaviors` - do you mind refactoring it to use that. That way can combine `--screenshot fullPage,fullPageAfterBehaviors` etc...

**Comment by fservida** [comment]
Reopening after adding changes

**Comment by fservida** [comment]
@ikreymer I've reimplemented the changes as suggested, hope this can be useful

**Review by tw4l — APPROVED** [review]
Making a new minor changes but overall looks good! Thank you for this.

**Comment by tw4l** [comment]
@fservida Looks like we need to run the auto-formatter before merging to resolve linting issues. Would you mind pushing a commit to this branch after running `yarn run format:fix`? Thanks! :)

**Comment by ikreymer** [comment]
Thinking should rename it to fullPageFinal instead of fullPageAfterBehaviors, since behaviors may not run in some circumstances, and this is more consistent with `final-to-warc` setting with have for text

**Review by ikreymer — APPROVED** [review]

**Pull request merged**
